//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduTestData.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EduTestEntities : DbContext
    {
        public EduTestEntities()
            : base("name=EduTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerBase> AnswerBases { get; set; }
        public virtual DbSet<Chapter> Chapters { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<QuestionBase> QuestionBases { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestInstance> TestInstances { get; set; }
        public virtual DbSet<TextareaAnswer> TextareaAnswers { get; set; }
        public virtual DbSet<TextareaQuestion> TextareaQuestions { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Variant> Variants { get; set; }
        public virtual DbSet<VariantAnswer> VariantAnswers { get; set; }
        public virtual DbSet<VariantQuestion> VariantQuestions { get; set; }
        public virtual DbSet<PersonalDetail> PersonalDetails1 { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Teacher> Teachers1 { get; set; }
    }
}
