//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduTestData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionBase()
        {
            this.AnswerBases = new HashSet<AnswerBase>();
            this.Tests = new HashSet<Test>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
        public bool Enabled { get; set; }
        public string Type { get; set; }
        public int Order { get; set; }
        public int TopicId { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerBase> AnswerBases { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual User User { get; set; }
        public virtual TextareaQuestion TextareaQuestion { get; set; }
        public virtual VariantQuestion VariantQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
    }
}
