//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduTestData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestInstance()
        {
            this.AnswerBases = new HashSet<AnswerBase>();
        }
    
        public int Id { get; set; }
        public int TestId { get; set; }
        public int UserId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerBase> AnswerBases { get; set; }
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
