//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduTestData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantAnswer
    {
        public int Id { get; set; }
        public Nullable<int> VariantId { get; set; }
    
        public virtual AnswerBase AnswerBase { get; set; }
        public virtual Variant Variant { get; set; }
    }
}
